services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: javatechie
    networks:
      - backend

  jenkins:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
