version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: javatechie
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-network

  jenkins:
    build: .
    container_name: jenkins-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - springboot-network

volumes:
  mysql_data:

networks:
  springboot-network:
    driver: bridge
